### PR TITLE
Added option to use AGAL 2 in Materials, added option to 'preTransfer' in Shaders

### PR DESCRIPTION
**Pull request by TomByrne**

### CODE REVIEW

**Comment by jgranick** [comment]
Do you know what the purpose of the `preTransfer` option is?

**Comment by TomByrne** [comment]
I think this was used to change the order that vertex shaders were being compiled in as the output value was being written before any custom shader code could be executed (added by `addMethod`).

As I can't really speak to this though I will create a new pull request with just the AGAL 2 change.

**Comment by peteshand** [comment]
Hey Tom

I think I was talking to michal a few weeks ago about this. Basically his changes to ShaderCompiler aren't needed as you can already do this by using a class that extends AnimatorBase and AnimationSetBase, take a look at https://github.com/openfl/away3d/blob/master/away3d/animators/VertexAnimator.hx

I guess for your changes maybe split them out into a separate pull request

**Comment by TomByrne** [comment]
No problem, thanks guys.

**Pull request closed without merging**
